
export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_USER = "AUTH_USER";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL"; 
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_INITITATE_LOGOUT = "AUTH_INITITATE_LOGOUT";
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const SAVE_USER_DATA = 'SAVE_USER_DATA';
export const DELETE_USER_DATA = 'DELETE_USER_DATA';
export const PHOTO_START = 'PHOTO_START';
export const PHOTO_FINISH = 'PHOTO_FINISH'

export const FETCH_ALL_VEHICLES_SUCCESS = 'FETCH_ALL_VEHICLES_SUCCESS';
export const FETCH_ALL_VEHICLES_START = 'FETCH_ALL_VEHICLES_START';
export const FETCH_ALL_VEHICLES_FAIL = 'FETCH_ALL_VEHICLES_FAIL';
export const FETCH_VEHICLES = 'FETCH_VEHICLES';
export const CARD_CLICK = 'ON_CARD_CLICK';
export const CLEAR = 'ON_CLEAR';
export const ON_VEHICLE_ID = 'ON_VEHICLE_ID';