
export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_USER = "AUTH_USER";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL"; 
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_INITITATE_LOGOUT = "AUTH_INITITATE_LOGOUT";
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const SAVE_USER_DATA = 'SAVE_USER_DATA';
export const DELETE_USER_DATA = 'DELETE_USER_DATA';
export const PHOTO_START = 'PHOTO_START';
export const PHOTO_FINISH = 'PHOTO_FINISH'

export const FETCH_ALL_VEHICLES_SUCCESS = 'FETCH_ALL_VEHICLES_SUCCESS';
export const FETCH_ALL_VEHICLES_START = 'FETCH_ALL_VEHICLES_START';
export const FETCH_ALL_VEHICLES_FAIL = 'FETCH_ALL_VEHICLES_FAIL';
export const FETCH_VEHICLES = 'FETCH_VEHICLES';
export const CARD_CLICK = 'ON_CARD_CLICK';
export const CLEAR = 'ON_CLEAR';
export const ON_VEHICLE_ID = 'ON_VEHICLE_ID';
export const START_DATE = 'START_DATE';
export const END_DATE = 'END_DATE';
export const TYPE_OF_PAYMENT = 'TYPE_OF_PAYMENT';
export const FETCH_SELECTED_VEHICLES = 'FETCH_SELECTED_VEHICLES';
export const SAVE_OWNER_BANK_ACCOUNT_NO = 'SAVE_OWNER_BANK_ACCOUNT_NO';
export const MY_VEHICLES = 'MY_VEHICLES';
export const VEHICLE_HISTORY = 'VEHICLE_HISTORY';

export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const UPDATE_ITEMS = 'UPDATE_ITEMS';
export const PRODUCT_CLICK = 'PRODUCT_CLICK';
export const CART_DETAILS = 'CART_DETAILS';
export const SET_TO_ZERO = 'SET_TO_ZERO';
export const ALREADY_ADDED_TO_CART = 'ALREADY_ADDED_TO_CART';
export const SINGLE_ITEM = 'SINGLE_ITEM';
export const QUANTITY = 'QUANTITY';
export const REMOVE_ITEM_CART = 'REMOVE_ITEM_CART';
export const CART_AMOUNT = 'CART_AMOUNT';
export const NO_OF_DAYS = 'NO_OF_DAYS';
export const ALERT_CONTROL = 'ALERT_CONTROL'

export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const DELETE_LOCAL_STORAGE = 'DELETE_LOCAL_STORAGE';